// NGINX language configuration
export const nginxLanguageConfig = {
  comments: {
    lineComment: "#",
  },
  brackets: [
    ["{", "}"],
    ["[", "]"],
  ],
  autoClosingPairs: [
    { open: "{", close: "}" },
    { open: "[", close: "]" },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
  ],
  surroundingPairs: [
    { open: "{", close: "}" },
    { open: "[", close: "]" },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
  ],
  indentationRules: {
    increaseIndentPattern: /^\s*\{/,
    decreaseIndentPattern: /^\s*\}/,
  },
};

// NGINX language definition
export const nginxLanguageDefinition = {
  defaultToken: "",
  tokenPostfix: ".nginx",

  keywords: [
    "server",
    "location",
    "upstream",
    "http",
    "events",
    "mail",
    "stream",
    "listen",
    "server_name",
    "root",
    "index",
    "try_files",
    "proxy_pass",
    "proxy_set_header",
    "proxy_redirect",
    "proxy_buffering",
    "proxy_cache",
    "fastcgi_pass",
    "fastcgi_param",
    "uwsgi_pass",
    "scgi_pass",
    "access_log",
    "error_log",
    "log_format",
    "gzip",
    "gzip_types",
    "ssl_certificate",
    "ssl_certificate_key",
    "ssl_protocols",
    "ssl_ciphers",
    "ssl_prefer_server_ciphers",
    "ssl_session_cache",
    "ssl_session_timeout",
    "client_max_body_size",
    "client_body_buffer_size",
    "client_header_buffer_size",
    "large_client_header_buffers",
    "keepalive_timeout",
    "keepalive_requests",
    "send_timeout",
    "proxy_connect_timeout",
    "proxy_send_timeout",
    "proxy_read_timeout",
    "fastcgi_connect_timeout",
    "fastcgi_send_timeout",
    "fastcgi_read_timeout",
    "uwsgi_connect_timeout",
    "uwsgi_send_timeout",
    "uwsgi_read_timeout",
    "scgi_connect_timeout",
    "scgi_send_timeout",
    "scgi_read_timeout",
    "limit_req_zone",
    "limit_req",
    "limit_conn_zone",
    "limit_conn",
    "auth_basic",
    "auth_basic_user_file",
    "auth_request",
    "add_header",
    "expires",
    "etag",
    "if_modified_since",
    "rewrite",
    "return",
    "break",
    "last",
    "permanent",
    "redirect",
    "include",
    "deny",
    "allow",
    "satisfy",
    "internal",
    "autoindex",
    "autoindex_exact_size",
    "autoindex_localtime",
    "charset",
    "charset_types",
    "source_charset",
    "sub_filter",
    "sub_filter_once",
    "sub_filter_types",
    "proxy_hide_header",
    "proxy_pass_request_headers",
    "proxy_pass_request_body",
    "fastcgi_hide_header",
    "fastcgi_pass_request_headers",
    "fastcgi_pass_request_body",
    "uwsgi_hide_header",
    "uwsgi_pass_request_headers",
    "uwsgi_pass_request_body",
    "scgi_hide_header",
    "scgi_pass_request_headers",
    "scgi_pass_request_body",
    "proxy_intercept_errors",
    "fastcgi_intercept_errors",
    "uwsgi_intercept_errors",
    "scgi_intercept_errors",
    "proxy_next_upstream",
    "proxy_next_upstream_tries",
    "proxy_next_upstream_timeout",
    "proxy_next_upstream_error",
    "proxy_next_upstream_timeout",
    "upstream_hash",
    "upstream_ip_hash",
    "upstream_least_conn",
    "upstream_random",
    "upstream_fair",
    "upstream_keepalive",
    "upstream_zone",
    "map",
    "split_clients",
    "geo",
    "types",
    "variables_hash_max_size",
    "variables_hash_bucket_size",
    "server_names_hash_max_size",
    "server_names_hash_bucket_size",
    "client_header_timeout",
    "client_body_timeout",
    "sendfile",
    "tcp_nopush",
    "tcp_nodelay",
    "reset_timedout_connection",
    "lingering_time",
    "lingering_timeout",
    "lingering_close",
    "keepalive_disable",
    "keepalive_requests",
    "keepalive_timeout",
    "send_timeout",
    "client_max_body_size",
    "client_body_buffer_size",
    "client_header_buffer_size",
    "large_client_header_buffers",
    "client_body_timeout",
    "client_header_timeout",
    "ignore_invalid_headers",
    "underscores_in_headers",
    "merge_slashes",
    "msie_padding",
    "msie_refresh",
    "open_file_cache",
    "open_file_cache_errors",
    "open_file_cache_min_uses",
    "open_file_cache_valid",
    "optimize_server_names",
    "postpone_output",
    "recursive_error_pages",
    "request_pool_size",
    "reset_timedout_connection",
    "send_lowat",
    "send_timeout",
    "sendfile",
    "sendfile_max_chunk",
    "tcp_nodelay",
    "tcp_nopush",
    "types_hash_max_size",
    "types_hash_bucket_size",
    "underscores_in_headers",
    "variables_hash_max_size",
    "variables_hash_bucket_size",
  ],

  directives: [
    "on",
    "off",
    "always",
    "error",
    "warn",
    "info",
    "debug",
    "notice",
    "crit",
    "emerg",
    "alert",
    "http",
    "https",
    "smtp",
    "pop3",
    "imap",
    "tcp",
    "udp",
    "unix",
    "block",
    "none",
    "any",
    "all",
    "default",
    "main",
    "events",
    "mail",
    "stream",
    "upstream",
    "server",
    "location",
    "if",
    "limit_except",
    "try_files",
    "return",
    "rewrite",
    "break",
    "last",
    "permanent",
    "redirect",
    "internal",
    "deny",
    "allow",
    "satisfy",
    "autoindex",
    "charset",
    "expires",
    "add_header",
    "etag",
    "if_modified_since",
    "sub_filter",
    "proxy_hide_header",
    "fastcgi_hide_header",
    "uwsgi_hide_header",
    "scgi_hide_header",
    "proxy_intercept_errors",
    "fastcgi_intercept_errors",
    "uwsgi_intercept_errors",
    "scgi_intercept_errors",
    "proxy_next_upstream",
    "upstream_hash",
    "upstream_ip_hash",
    "upstream_least_conn",
    "upstream_random",
    "upstream_fair",
    "upstream_keepalive",
    "upstream_zone",
    "map",
    "split_clients",
    "geo",
    "types",
    "include",
  ],

  variables: [
    "$args",
    "$binary_remote_addr",
    "$body_bytes_sent",
    "$bytes_sent",
    "$connection",
    "$connection_requests",
    "$connections_reading",
    "$connections_waiting",
    "$connections_writing",
    "$content_length",
    "$content_type",
    "$cookie_*",
    "$document_filename",
    "$document_name",
    "$document_root",
    "$document_uri",
    "$fastcgi_path_info",
    "$fastcgi_script_name",
    "$geoip_city",
    "$geoip_country_code",
    "$geoip_country_name",
    "$geoip_dma_code",
    "$geoip_latitude",
    "$geoip_longitude",
    "$geoip_org",
    "$geoip_postal_code",
    "$geoip_region",
    "$geoip_region_name",
    "$host",
    "$hostname",
    "$http_*",
    "$https",
    "$is_args",
    "$limit_rate",
    "$memcached_key",
    "$nginx_version",
    "$pid",
    "$pipe",
    "$proxy_add_x_forwarded_for",
    "$proxy_host",
    "$proxy_port",
    "$proxy_protocol_addr",
    "$proxy_protocol_port",
    "$proxy_protocol_server_addr",
    "$proxy_protocol_server_port",
    "$query_string",
    "$realpath_root",
    "$remote_addr",
    "$remote_port",
    "$remote_user",
    "$request",
    "$request_body",
    "$request_body_file",
    "$request_completion",
    "$request_filename",
    "$request_id",
    "$request_length",
    "$request_method",
    "$request_time",
    "$request_uri",
    "$scheme",
    "$sent_http_*",
    "$sent_trailer_*",
    "$server_addr",
    "$server_name",
    "$server_port",
    "$server_protocol",
    "$status",
    "$tcpinfo_rtt",
    "$tcpinfo_rttvar",
    "$tcpinfo_snd_cwnd",
    "$tcpinfo_rcv_space",
    "$time_iso8601",
    "$time_local",
    "$upstream_addr",
    "$upstream_bytes_received",
    "$upstream_bytes_sent",
    "$upstream_cache_status",
    "$upstream_connect_time",
    "$upstream_cookie_*",
    "$upstream_header_*",
    "$upstream_http_*",
    "$upstream_response_length",
    "$upstream_response_time",
    "$upstream_status",
    "$upstream_trailer_*",
    "$upstream_addr",
    "$upstream_bytes_received",
    "$upstream_bytes_sent",
    "$upstream_cache_status",
    "$upstream_connect_time",
    "$upstream_cookie_*",
    "$upstream_header_*",
    "$upstream_http_*",
    "$upstream_response_length",
    "$upstream_response_time",
    "$upstream_status",
    "$upstream_trailer_*",
  ],

  tokenizer: {
    root: [
      // Comments
      [/#.*$/, "comment"],

      // Strings
      [/"/, "string", "@string_double"],
      [/'/, "string", "@string_single"],

      // Numbers
      [/\d+/, "number"],

      // Variables
      [/\$[a-zA-Z_][a-zA-Z0-9_]*/, "variable"],

      // Directives and keywords
      [
        /[a-zA-Z_][a-zA-Z0-9_]*/,
        {
          cases: {
            "@keywords": "keyword",
            "@directives": "keyword",
            "@default": "identifier",
          },
        },
      ],

      // Punctuation
      [/[{}[\]]/, "delimiter.bracket"],
      [/[;,]/, "delimiter"],

      // Whitespace
      { include: "@whitespace" },
    ],

    string_double: [
      [/[^\\"]+/, "string"],
      [/"/, "string", "@pop"],
    ],

    string_single: [
      [/[^\\']+/, "string"],
      [/'/, "string", "@pop"],
    ],

    whitespace: [[/[ \t\r\n]+/, "white"]],
  },
};

// Register the NGINX language
export function registerNginxLanguage() {
  // This will be called from the editor component when Monaco is available
  if (typeof window !== "undefined" && (window as any).monaco) {
    const monaco = (window as any).monaco;
    monaco.languages.register({ id: "nginx" });
    monaco.languages.setMonarchTokensProvider("nginx", nginxLanguageDefinition);
    monaco.languages.setLanguageConfiguration("nginx", nginxLanguageConfig);
  }
}
